/**
 * CompletedMessagesTab — read-only communication log shown in the
 * Messages tab of a completed (APPROVED / DENIED, auto-processed) case.
 *
 * Storyboard reference: CMS Demo Storyboard / src/components/CompletedCaseDetail.jsx
 * — the {tab === "messages"} block. Differs from the active-case
 * NoticesMessagesTab (no reply form, no RFI deadline banner) because all
 * messages on an auto-processed case were system-generated.
 */

import { useState } from 'react';
import { Check, FileText, Info } from 'lucide-react';
import type { CaseMessage } from '../../data/case-details';

interface CompletedMessagesTabProps {
  messages: ReadonlyArray<CaseMessage>;
  /** Called when user clicks the "View" button on an attachment. The
   *  parent decides what to render (typically the NoticeOfDecisionModal). */
  onViewAttachment?: (msg: CaseMessage, attachmentIndex: number) => void;
}

const TRUNCATE_LENGTH = 130;

const CHANNEL_COLORS: Record<string, string> = {
  Portal: 'bg-violet-50 text-violet-700',
  SMS: 'bg-pink-50 text-pink-700',
  Email: 'bg-sky-50 text-sky-700',
  Mail: 'bg-amber-50 text-amber-700',
  System: 'bg-slate-100 text-slate-700',
};

function channelClass(ch: string): string {
  return CHANNEL_COLORS[ch] ?? 'bg-slate-100 text-slate-700';
}

function StatusChecks({ status }: { status: CaseMessage['status'] }) {
  // Single check (gray) = delivered/received; double check (blue) = read.
  if (status === 'read') {
    return (
      <span aria-label="Read" className="inline-flex items-center" style={{ color: 'var(--civic-accent-solid)' }}>
        <Check className="w-3 h-3 -mr-1" aria-hidden="true" />
        <Check className="w-3 h-3" aria-hidden="true" />
      </span>
    );
  }
  if (status === 'delivered' || status === 'received') {
    return (
      <span aria-label="Delivered" className="inline-flex items-center text-muted-foreground">
        <Check className="w-3 h-3 -mr-1" aria-hidden="true" />
        <Check className="w-3 h-3" aria-hidden="true" />
      </span>
    );
  }
  if (status === 'sent') {
    return (
      <span aria-label="Sent" className="inline-flex items-center text-muted-foreground">
        <Check className="w-3 h-3" aria-hidden="true" />
      </span>
    );
  }
  return null;
}

export function CompletedMessagesTab({ messages, onViewAttachment }: CompletedMessagesTabProps) {
  const [expanded, setExpanded] = useState<Set<string>>(new Set());
  const [channelFilter, setChannelFilter] = useState<string>('all');

  const channels = Array.from(new Set(messages.map((m) => m.channel)));
  const filtered = channelFilter === 'all' ? messages : messages.filter((m) => m.channel === channelFilter);

  const toggle = (id: string) =>
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });

  return (
    <div className="space-y-4">
      {/* Read-only banner */}
      <div className="rounded-md border border-border bg-muted/30 p-3 flex items-start gap-2.5">
        <Info className="w-4 h-4 text-muted-foreground mt-0.5 flex-shrink-0" aria-hidden="true" />
        <div>
          <p className="text-xs font-semibold text-foreground">Read-only communication log</p>
          <p className="text-xs text-muted-foreground mt-0.5">
            This case was auto-processed. All messages were generated by the system. Reply is unavailable.
          </p>
        </div>
      </div>

      {/* Channel filter — only shown when there's more than one channel on file */}
      {channels.length > 1 && (
        <div className="flex items-center gap-2 flex-wrap">
          {['all', ...channels].map((ch) => {
            const isActive = channelFilter === ch;
            return (
              <button
                key={ch}
                type="button"
                onClick={() => setChannelFilter(ch)}
                className={
                  isActive
                    ? 'px-3 py-1.5 rounded-md text-xs font-medium border border-transparent text-white'
                    : 'px-3 py-1.5 rounded-md text-xs font-medium border border-border bg-card text-muted-foreground hover:border-muted-foreground'
                }
                style={isActive ? { backgroundColor: 'var(--civic-accent-solid)' } : undefined}
              >
                {ch === 'all' ? 'All' : ch}
              </button>
            );
          })}
        </div>
      )}

      {/* Empty state */}
      {messages.length === 0 && (
        <div className="text-center py-10 text-sm text-muted-foreground bg-card rounded-md border border-border">
          No messages on file.
        </div>
      )}

      {/* Message cards */}
      <div className="space-y-3">
        {filtered.map((m) => {
          const isOut = m.direction === 'outbound';
          const isExpanded = expanded.has(m.id);
          const canExpand = m.content.length > TRUNCATE_LENGTH;
          const displayContent = canExpand && !isExpanded ? `${m.content.slice(0, TRUNCATE_LENGTH)}…` : m.content;
          return (
            <div key={m.id} className="rounded-md border border-border bg-card p-4 relative overflow-hidden">
              {/* Left accent bar — blue for outbound, green for inbound */}
              <span
                aria-hidden="true"
                className="absolute left-0 top-0 bottom-0 w-1"
                style={{
                  backgroundColor: isOut ? 'var(--civic-accent-solid)' : '#16a34a',
                  opacity: 0.6,
                }}
              />

              <div className="flex items-start justify-between gap-3 mb-2">
                <div className="flex items-center gap-2 flex-wrap">
                  <span
                    className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium ${channelClass(
                      m.channel,
                    )}`}
                  >
                    {m.channel}
                  </span>
                  <span className="text-xs text-muted-foreground">{isOut ? 'Outbound' : 'Inbound'}</span>
                  <StatusChecks status={m.status} />
                </div>
                <div className="text-right flex-shrink-0">
                  <p className="text-xs text-muted-foreground">{m.timestamp}</p>
                  <p className="text-xs text-muted-foreground/70 mt-0.5">{m.sender}</p>
                </div>
              </div>

              {m.subject && <p className="text-sm font-semibold text-foreground mb-1.5">{m.subject}</p>}

              <p className="text-sm leading-relaxed text-foreground">{displayContent}</p>

              {canExpand && (
                <button
                  type="button"
                  onClick={() => toggle(m.id)}
                  className="text-xs font-medium mt-1.5 hover:underline"
                  style={{ color: 'var(--civic-accent-solid)' }}
                >
                  {isExpanded ? 'Show less ▲' : 'Show more ▼'}
                </button>
              )}

              {m.attachments && m.attachments.length > 0 && (
                <div className="mt-3 pt-3 border-t border-border space-y-2">
                  {m.attachments.map((att, ai) => (
                    <div
                      key={`${m.id}-${ai}`}
                      className="flex items-center justify-between bg-card rounded-md border border-border px-3 py-2"
                    >
                      <div className="flex items-center gap-2 min-w-0">
                        <FileText className="w-4 h-4 text-muted-foreground shrink-0" aria-hidden="true" />
                        <div className="min-w-0">
                          <p className="text-xs font-medium text-foreground truncate">{att.name}</p>
                          <p className="text-xs text-muted-foreground">{att.size}</p>
                        </div>
                      </div>
                      <button
                        type="button"
                        onClick={() => onViewAttachment?.(m, ai)}
                        className="text-xs font-medium px-2.5 py-1 rounded-md border border-border bg-card hover:bg-muted/40 shrink-0 ml-2"
                        title="Preview notice as sent"
                      >
                        View
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
